- name: Message 1
  ansible.builtin.debug:
    msg: "Hi, From msg 1"

- name: set the os fact
  ansible.builtin.set_fact:
    OS: "debian"

- name: Message 2
  ansible.builtin.debug:
    msg: "Hi, From msg 2"

- name: Message 3
  ansible.builtin.debug:
    msg: "Hi, From msg 3"