- name: Install maven
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: 
  - maven
  - mysql

- name: install shipping dependencies
  ansible.builtin.command: mvn clean package 
  args:
    chdir: /app

- name: Install dependencies
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app